local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ef', builtin.find_files, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>es', function() 
require('lualine').setup()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
